#!/usr/bin/env bash
# shellcheck shell=bash disable=SC2016

set -euo pipefail

readonly host="${DOCKER_HOST:-}"
readonly config="${STATIC_CONFIG_PATH:-}"
readonly pattern='(?i)([a-z]+://)([\x10-\x7E]+)'

socket="$(rg --trim --line-regexp --no-column --no-line-number --replace='$2' "${pattern}" <<< "${host}")"

if [[ -z "${config}" ]] || [[ ! -f "${config}" ]]; then
  exit 0
fi

if [[ -n "${DOCKER_HOST}" ]] && [[ -S "${socket}" ]]; then
  yq -iPo yaml 'with(.providers.docker; .endpoint = env(DOCKER_HOST))' "${config}"
  printf '[traefik-config] set `.providers.docker.endpoint` to: %s\n' "${DOCKER_HOST}"
else
  yq -iPo yaml 'del(.providers.docker)' "${config}"
  printf '[traefik-config] removed `.providers.docker` from traefik config\n'
fi
